"""add profesional_email to clases

Revision ID: 96ade852c801
Revises: c602547ab5bb
Create Date: 2026-05-18 00:31:45.146026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ade852c801'
down_revision: Union[str, Sequence[str], None] = 'c602547ab5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clases', sa.Column('profesional_email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clases', 'profesional_email')
    # ### end Alembic commands ###
