"""initial schema

Revision ID: c602547ab5bb
Revises:
Create Date: 2026-05-17 15:28:59.200099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c602547ab5bb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "zona",
            sa.Enum("superior", "medio", "inferior", name="zonaenum"),
            nullable=False,
        ),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("hora", sa.String(length=5), nullable=False),
        sa.Column("cupo_max", sa.Integer(), nullable=False),
        sa.Column("inscritos", sa.Integer(), nullable=True),
        sa.Column("cancelada", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clases_fecha"), "clases", ["fecha"], unique=False)
    op.create_index(op.f("ix_clases_id"), "clases", ["id"], unique=False)
    op.create_index(op.f("ix_clases_zona"), "clases", ["zona"], unique=False)
    op.create_table(
        "configuracion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("precio", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "turnos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.String(length=10), nullable=False),
        sa.Column("hora", sa.String(length=5), nullable=False),
        sa.Column("zona", sa.String(length=20), nullable=False),
        sa.Column("medio_pago", sa.String(length=30), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_turnos_fecha"), "turnos", ["fecha"], unique=False)
    op.create_index(op.f("ix_turnos_id"), "turnos", ["id"], unique=False)
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=True),
        sa.Column("apellido", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("fecha_nacimiento", sa.Date(), nullable=True),
        sa.Column("rol", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_email"), "usuarios", ["email"], unique=True)
    op.create_index(op.f("ix_usuarios_id"), "usuarios", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usuarios_id"), table_name="usuarios")
    op.drop_index(op.f("ix_usuarios_email"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_turnos_id"), table_name="turnos")
    op.drop_index(op.f("ix_turnos_fecha"), table_name="turnos")
    op.drop_table("turnos")
    op.drop_table("configuracion")
    op.drop_index(op.f("ix_clases_zona"), table_name="clases")
    op.drop_index(op.f("ix_clases_id"), table_name="clases")
    op.drop_index(op.f("ix_clases_fecha"), table_name="clases")
    op.drop_table("clases")
    # ### end Alembic commands ###
